insert into public.vehicles (
  id,
  brand,
  model,
  title,
  year,
  mileage,
  fuel,
  transmission,
  price_czk,
  category,
  body_type,
  color,
  power_kw,
  engine,
  license_plate,
  status,
  is_featured,
  image_url,
  description
) values
  (
    '11111111-1111-4111-8111-111111111111',
    'BMW',
    'X6 M',
    'Competition 460 kW',
    2024,
    8200,
    'Benzin',
    'Automat',
    3299000,
    'SUV / 4x4',
    'SUV',
    'Černá metalíza',
    460,
    '4.4 V8 M TwinPower Turbo',
    '1AM ZENJA',
    'published',
    false,
    '/images/car-bmw-x6-black.jpg',
    'Prémiové sportovní SUV v černé metalíze připravené pro osobní prohlídku.'
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'BMW',
    'X4 M',
    'Competition 375 kW',
    2024,
    5900,
    'Benzin',
    'Automat',
    2799000,
    'SUV / 4x4',
    'SUV kupé',
    'Bílá perleť',
    375,
    '3.0 R6 M TwinPower Turbo',
    '1AM RYSKA',
    'published',
    false,
    '/images/car-bmw-x4-white.jpg',
    'Výrazné sportovní SUV kupé v bílé perleti s jasným původem.'
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'Škoda',
    'Superb Combi',
    '2.0 TDI 147 kW DSG L&K',
    2021,
    112000,
    'Nafta',
    'Automat',
    569000,
    'Osobní vozy',
    'Kombi',
    'Šedá metalíza',
    147,
    '2.0 TDI',
    null,
    'published',
    true,
    '/images/car-superb.jpg',
    'Prostorný kombi vůz s automatickou převodovkou a prověřenou historií.'
  ),
  (
    '44444444-4444-4444-8444-444444444444',
    'BMW',
    'X3',
    'xDrive 20d 140 kW',
    2020,
    98500,
    'Nafta',
    'Automat',
    675000,
    'SUV / 4x4',
    'SUV',
    'Bílá',
    140,
    '2.0d',
    null,
    'published',
    true,
    '/images/car-bmw-x3.jpg',
    'Oblíbené prémiové SUV s pohonem všech kol a automatickou převodovkou.'
  ),
  (
    '55555555-5555-4555-8555-555555555555',
    'Volkswagen',
    'Tiguan',
    '2.0 TDI 110 kW 4MOTION',
    2019,
    125000,
    'Nafta',
    'Automat',
    545000,
    'SUV / 4x4',
    'SUV',
    'Šedá',
    110,
    '2.0 TDI',
    null,
    'published',
    true,
    '/images/car-tiguan.jpg',
    'Praktické SUV s pohonem 4MOTION a úsporným naftovým motorem.'
  ),
  (
    '66666666-6666-4666-8666-666666666666',
    'Audi',
    'A4',
    '35 TFSI 110 kW S tronic',
    2020,
    76300,
    'Benzin',
    'Automat',
    548000,
    'Osobní vozy',
    'Sedan',
    'Stříbrná',
    110,
    '35 TFSI',
    null,
    'published',
    true,
    '/images/car-audi-a4.jpg',
    'Elegantní sedan s benzinovým motorem a automatickou převodovkou.'
  ),
  (
    '77777777-7777-4777-8777-777777777777',
    'Volvo',
    'XC60',
    'B4 AWD Momentum Pro',
    2022,
    43800,
    'Hybrid',
    'Automat',
    899000,
    'SUV / 4x4',
    'SUV',
    'Černá',
    145,
    'B4 mild-hybrid',
    null,
    'published',
    false,
    '/images/car-volvo-xc60.jpg',
    'Bezpečné prémiové SUV s úsporným mild-hybridním pohonem.'
  )
on conflict (id) do update set
  brand = excluded.brand,
  model = excluded.model,
  title = excluded.title,
  year = excluded.year,
  mileage = excluded.mileage,
  fuel = excluded.fuel,
  transmission = excluded.transmission,
  price_czk = excluded.price_czk,
  category = excluded.category,
  body_type = excluded.body_type,
  color = excluded.color,
  power_kw = excluded.power_kw,
  engine = excluded.engine,
  license_plate = excluded.license_plate,
  status = excluded.status,
  is_featured = excluded.is_featured,
  image_url = excluded.image_url,
  description = excluded.description;

update public.vehicles as vehicle
set
  stk_valid_until = specs.stk_valid_until,
  origin_country = specs.origin_country,
  first_registration = specs.first_registration,
  owners_count = specs.owners_count,
  service_history = specs.service_history,
  accident_history = specs.accident_history,
  equipment = specs.equipment,
  condition_note = specs.condition_note,
  warranty_note = specs.warranty_note,
  emission_standard = specs.emission_standard,
  drivetrain = specs.drivetrain,
  doors_count = specs.doors_count,
  seats_count = specs.seats_count
from (
  values
    (
      '11111111-1111-4111-8111-111111111111'::uuid,
      '2028-03-31'::date,
      'Německo',
      '2024-03-12'::date,
      1,
      'Nový modelový ročník, servisní historie bude doložena podle dokumentace.',
      'Stav a historie budou ověřeny před předáním.',
      array['M Competition', 'xDrive', 'M sportovní sedadla', 'Laserové světlomety', 'Head-up displej']::text[],
      'Prémiový sportovní vůz s nízkým nájezdem.',
      'Rozsah záruky bude potvrzen podle dokumentace vozu.',
      'Euro 6e',
      'xDrive',
      5,
      5
    ),
    (
      '33333333-3333-4333-8333-333333333333'::uuid,
      '2027-04-30'::date,
      'Česká republika',
      '2021-03-18'::date,
      1,
      'Servisní záznamy dle dostupné dokumentace vozu.',
      'Bez evidovaného vážného poškození v dostupných podkladech.',
      array['LED Matrix světlomety', 'Adaptivní tempomat', 'Vyhřívaná sedadla', 'Navigace', 'Parkovací kamera']::text[],
      'Velmi dobrý stav odpovídající stáří a nájezdu.',
      'Rozsah záruky bude potvrzen při osobní prohlídce.',
      'Euro 6d',
      'Přední pohon',
      5,
      5
    ),
    (
      '77777777-7777-4777-8777-777777777777'::uuid,
      '2027-09-30'::date,
      'Česká republika',
      '2022-08-05'::date,
      1,
      'Servisní historie podle dostupné dokumentace.',
      'Bez evidovaného vážného poškození v dostupných podkladech.',
      array['AWD', 'Bezpečnostní asistenti Volvo', 'Vyhřívaná sedadla', 'Navigace', 'Elektrické víko kufru']::text[],
      'Prémiové SUV s velmi dobrým komfortem a zachovalým interiérem.',
      'Možnost individuálně prověřit další záruční krytí.',
      'Euro 6d',
      'AWD',
      5,
      5
    )
) as specs(
  id,
  stk_valid_until,
  origin_country,
  first_registration,
  owners_count,
  service_history,
  accident_history,
  equipment,
  condition_note,
  warranty_note,
  emission_standard,
  drivetrain,
  doors_count,
  seats_count
)
where vehicle.id = specs.id;

insert into public.services (
  slug,
  title,
  description,
  status,
  badge,
  sort_order
) values
  (
    'vykup',
    'Výkup vozu',
    'Vykoupíme váš vůz rychle, férově a za nejlepší možnou cenu.',
    'active',
    null,
    10
  ),
  (
    'pojisteni',
    'Pojištění',
    'Zajistíme pro vás výhodné pojištění vozidla během pár minut.',
    'active',
    null,
    20
  ),
  (
    'servis',
    'Servis',
    'Profesionální servisní péče pro všechny značky vozů.',
    'active',
    null,
    30
  ),
  (
    'dovoz',
    'Dovoz vozů',
    'Dovezeme vám vůz ze zahraničí podle vašich představ.',
    'active',
    null,
    40
  ),
  (
    'garance',
    'Garance původu',
    'Garantujeme původ vozu a prověřenou servisní historii.',
    'active',
    null,
    50
  ),
  (
    'financovani',
    'Financování',
    'Možnost financování připravujeme. Služba bude dostupná až po dokončení spolupráce s finančními partnery.',
    'coming_soon',
    'Připravujeme',
    60
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  badge = excluded.badge,
  sort_order = excluded.sort_order;
